In [1]:
import numpy as np

In [3]:
ar=np.arange(0,11)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
ar[8]

8

In [18]:
ar[:4]
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
ar[:6]

array([0, 1, 2, 3, 4, 5])

In [19]:
ar[0:5]=100
ar

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [20]:
ar=np.arange(0,11)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
s=ar[0:6]
s

array([0, 1, 2, 3, 4, 5])

In [24]:
s[:]=111
s

array([111, 111, 111, 111, 111, 111])

In [25]:
ar

array([111, 111, 111, 111, 111, 111,   6,   7,   8,   9,  10])

In [30]:
ar_copy=ar.copy()
ar_copy

array([111, 111, 111, 111, 111, 111,   6,   7,   8,   9,  10])

In [31]:
ar_copy[:]=99
ar_copy

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [32]:
ar

array([111, 111, 111, 111, 111, 111,   6,   7,   8,   9,  10])

In [33]:
ar_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])
ar_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [34]:
ar_2d[2,2]

45

In [35]:
ar_2d[0][1]

10

In [36]:
ar_2d[1]

array([20, 25, 30])

In [37]:
ar_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [38]:
ar_2d[2,:]

array([35, 40, 45])

In [39]:
ar_2d=np.zeros((10,10))
ar_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [40]:
ar_length=ar_2d.shape[1]
ar_length

10

In [41]:
for i in range(ar_length):
    ar_2d[i]=i
ar_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [43]:
c=ar_2d[[2,4,6,8]]
c

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [45]:
a=ar_2d[[6,4,2,7]]
a

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [48]:
a[0,3:5]

array([6., 6.])

In [49]:
a=ar_2d[2::2,::2]
a

array([[2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8.]])

In [51]:
ar=np.arange(1,11)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
bool_ar=ar>4
bool_ar

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [56]:
ar[bool_ar]

array([ 5,  6,  7,  8,  9, 10])

In [57]:
x=2
ar[ar>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
ar+ar

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [59]:
ar*ar

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [60]:
ar/ar

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [61]:
ar-ar

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [62]:
1/ar

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

In [64]:
ar**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [65]:
np.sqrt(ar)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [66]:
np.exp(ar)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [67]:
np.max(ar)

10

In [68]:
np.min(ar)

1

In [69]:
np.std(ar)

2.8722813232690143

In [70]:
np.log(ar)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [71]:
np.sin(ar)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])